In [2]:
import numpy as np 


In [5]:
x=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [6]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
print('value at [0][0], [0][1] : ', x[0:1,0:2])

value at [0][0], [0][1] :  [[0 1]]


In [9]:
print('value at [0][2],[0],[3]',x[0:1,1:4])

value at [0][2],[0],[3] [[1 2 3]]


In [11]:
print('value at [1][0] :',x[1:2,0:1])

value at [1][0] : [[4]]


In [12]:
print("values at [0][1],[0][2],[0][3] :",x[0:1,1:4] )

values at [0][1],[0][2],[0][3] : [[1 2 3]]


In [15]:
print("values at [1][1],[1,2],[1,3] : " ,x[1:2,1:4])

values at [1][1],[1,2],[1,3] :  [[5 6 7]]


In [16]:
print(x[1:3,1:4])

[[ 5  6  7]
 [ 9 10 11]]


In [17]:
y=np.array([[8,20,24,25],[30,35,36,40],[42,42,47,50],[49,51,52,53]])

In [18]:
print(y)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 42 47 50]
 [49 51 52 53]]


In [19]:
print("values at 35,36,43,47 :",y[1:3,1:3])

values at 35,36,43,47 : [[35 36]
 [42 47]]


In [20]:
print(y[2: ,1: ])

[[42 47 50]
 [51 52 53]]


In [21]:
print(y[0:2,2: ])

[[24 25]
 [36 40]]
